name: Check that docs build
on:
  pull_request:
    paths:
      - './docs/**.png'
      - './docs/README.md'
      - './docs/book/**.yml'
      - './docs/book/**.bib'
      - './docs/book/content/calibration/images/**.png'
      - '**.md'
      - './docs/book/content/api/**.rst'
      - './ogidn/**.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: ogidn-dev
          environment-file: environment.yml
          python-version: "3.13"
          auto-activate-base: false

      - name: Build # Build Jupyter Book
        shell: bash -l {0}
        run: |
          pip install jupyter-book>=0.11.3
          pip install sphinxcontrib-bibtex>=2.0.0
          pip install -e .
          python -m ipykernel install --user --name=ogidn-dev
          jb build ./docs/book
